- 1.1.14
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight,
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control,
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _dpi-sliding: 88
  _modelId: B03400000000
  _sensitive: {divert-keys: true, dpi: false, hires-scroll-mode: false, hires-smooth-invert: false, hires-smooth-resolution: true, reprogrammable-keys: true,
    scroll-ratchet: false, smart-shift: false, thumb-scroll-invert: false, thumb-scroll-mode: false}
  _serial: 9F0232F9
  _unitId: 9F0232F9
  _wpid: B034
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 2, 195: 1, 196: 1}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 196, 86: 86, 195: 196, 196: 82}
  scroll-ratchet: 2
  smart-shift: 20
  thumb-scroll-invert: true
  thumb-scroll-mode: false
